language: objective-c

osx_image: xcode11.3
env:
  matrix:
    - TEST_SDK=iphonesimulator13.2 OS=13.2 NAME='iPhone XR'
    - TEST_SDK=iphonesimulator13.1 OS=13.2 NAME='iPhone 7'

script:
  - set -o pipefail && xcodebuild test -enableCodeCoverage YES -project SwiftLib.xcodeproj -scheme SwiftLib -sdk $TEST_SDK -destination "platform=iOS Simulator,OS=$OS,name=$NAME" ONLY_ACTIVE_ARCH=YES